# ponytail: doc deep-links blanked pending a loom docs site; fill in when one exists.
website = "https://github.com/sri-venkat-22/loom"
add_all_files = ""
edit_errors = ""
git = ""
enable_playwright = ""
favicon = ""
model_warnings = ""
token_limits = ""
llms = ""
large_repos = ""
github_issues = "https://github.com/sri-venkat-22/loom/issues/new"
git_index_version = ""
install_properly = ""
analytics = ""
release_notes = ""
edit_formats = ""
models_and_keys = ""
