#!/usr/bin/env python
"""
Regenerate the loom/docs pages that are built from the code:

- options.md        (command line / config options, from loom.args)
- commands.md       (in-chat /commands, from loom.commands)
- model-aliases.md  (short model names, from loom.models.MODEL_ALIASES)

Run from the repo root after changing any of those: python scripts/gen_docs.py
"""

from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent / "loom" / "docs"

GENERATED = "<!-- Generated by scripts/gen_docs.py; do not edit by hand. -->\n\n"


def gen_options():
    from loom.args import get_md_help

    return GENERATED + """# Options reference

Every option can be given on the command line, in a `.loom.conf.yml` config file,
or as a `LOOM_*` environment variable (including in a `.env` file).
See [config.md](config.md) for how those sources are combined.

""" + get_md_help().strip() + "\n"


def gen_commands():
    from loom.commands import Commands
    from loom.io import InputOutput

    io = InputOutput(pretty=False, yes=True)
    commands = Commands(io, None)

    lines = [
        GENERATED,
        "# In-chat commands\n\n",
        "Type these at the loom prompt. Commands can be abbreviated to any unique prefix,",
        " so `/a` works for `/add` if nothing else starts with `a`.\n\n",
        "| Command | Description |\n",
        "|---|---|\n",
    ]
    for cmd in commands.get_commands():
        method = getattr(commands, f"cmd_{cmd[1:]}".replace("-", "_"), None)
        doc = " ".join((method.__doc__ or "").split()) if method else ""
        lines.append(f"| `{cmd}` | {doc} |\n")

    lines.append("""
## Entering multi-line messages

- Type `{` on its own line, then your message, then `}` on its own line.
- Or use `/multiline-mode` so Enter adds a newline and Meta+Enter (Esc then Enter) sends.
- Or use `/editor` to write the message in your `$EDITOR`.

## Shell shortcut

`!cmd` is the same as `/run cmd`: it runs a shell command and offers to add the output
to the chat.
""")
    return "".join(lines)


def gen_aliases():
    from loom.models import MODEL_ALIASES

    lines = [
        GENERATED,
        "# Model aliases\n\n",
        "These short names can be used anywhere a model name is accepted, for example",
        " `loom --model sonnet` or `/model gemini-3.1`.\n",
        "You can add your own with `--alias ALIAS:MODEL`.\n\n",
        "| Alias | Model |\n",
        "|---|---|\n",
    ]
    for alias, model in MODEL_ALIASES.items():
        lines.append(f"| `{alias}` | `{model}` |\n")
    return "".join(lines)


def main():
    pages = {
        "options.md": gen_options(),
        "commands.md": gen_commands(),
        "model-aliases.md": gen_aliases(),
    }
    for name, text in pages.items():
        (DOCS / name).write_text(text, encoding="utf-8")
        print(f"wrote {DOCS / name}")


if __name__ == "__main__":
    main()
